### PR TITLE
Refactor and improve code

### PR DESCRIPTION
**Pull request by jcelerier**
- Fix that nothing would build if including puara-utils in multiple files
- Put Calibration code in its own file so that code that does not use eigen does not have to install it
- Add missing default initialization in many places
- Add CI
- Remove some unneeded constructors - in modern C++ if a class looks like e.g. 

```c++
class Wrap
{
public:
  double min{};
  double max{};
  void f() { blabla; }
};
```

one can simply create it like: 

```c++
Wrap w1{-100., 456.};

or even better

Wrap w2{.min = -100., .max = 456.};
```

C++20 also allows to use () instead of {} for this but I think it is better to use {} as it will refuse to do any conversion that would loose precision unlike () which happily does a ton of implicit conversions)

### CODE REVIEW

**Comment by edumeneses** [comment]
Thanks for that work @jcelerier. 

We can merge as is if it's working (I didn't test it). 

However, I'm having second thoughts about creating a utils folder and separating the classes as we did with the descriptors. What do you think?

**Comment by jcelerier** [comment]
yes, great idea ! I'll do that

**Comment by jcelerier** [comment]
Ok, did a much more thorough cleanup and adapted the library structure to match more closely current expectations and standards in the C++ community

**Comment by jcelerier** [comment]
Ok, ci builds on Mac/Win/Linux I think we can safely merge :)
I noticed in the refactor that some functions disappeared though, added a few fixme in the code to bring them back to life @samamou

**Review by edumeneses — APPROVED** [review]
Looks good.

I fixed 1 silly .gitignore conflict

**Comment by jcelerier** [comment]
ty!

**Comment by edumeneses** [comment]
@jcelerier and @samamou , I noticed the refactored files don't have the latest editor name. 

Perhaps adding you/them to the head comments on each descriptor/utils file is a good idea?

**Comment by edumeneses** [comment]
@jcelerier , do we wait for @samamou 's review?

**Comment by samamou** [comment]
I think i will **need** to check for the functions that got removed when we were refactoring, I have some time tomorrow @edumeneses

**Review by samamou — APPROVED** [review]

**Comment by jcelerier** [comment]
build is broken :^)

**Comment by jcelerier** [comment]
all is green, ACK for me to merge ! congrats :)

**Comment by jcelerier** [comment]
Edu is it good for you ?

**Review by edumeneses — APPROVED** [review]

**Comment by jcelerier** [comment]
\o/

**Pull request merged**
